name: Build & Test

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths: [ 'src/**' ]
  pull_request:
    branches: [ 'main' ]
    paths: [ 'src/**' ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c release
    - name: Run tests
      run: dotnet test --no-build -c release --verbosity normal
