name: Publish Docs

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Release
    types:
      - completed

jobs:
  publish-docs:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Install Docfx
      run: dotnet tool install docfx -g
    - name: Build documentation
      run: docfx docs/docfx.json
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/_site
    - name: Deploy to Github Pages
      id: deployment
      uses: actions/deploy-pages@v1
